changes
ogeobubu/factservices pull request #1
Opened 2020-11-02 17:12 UTC by mosesfawole

2020-11-02 18:26 UTC, ogeobubu requested changes

2020-11-02 18:26 UTC, ogeobubu commented on about.html
> +        Eaque, facere.
[factservices-43a43727c756d53119e306eccf7a03588d6c2650.zip](https://github.com/ogeobubu/factservices/files/5477173/factservices-43a43727c756d53119e306eccf7a03588d6c2650.zip)

2020-11-02 20:14 UTC, mosesfawole reviewed
...

2020-11-03 02:55 UTC, ogeobubu commented on about.html
> +        Eaque, facere.
You've seen it right?

2020-11-03 03:18 UTC, mosesfawole commented
i can't merge the pull request, its displaying this *Only those with write access to this repository can merge pull requests.*

2020-11-03 15:19 UTC, merged

2020-11-03 15:20 UTC, ogeobubu commented
I just merged now